# Generated by Django 5.0.4 on 2024-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdMetrics', '0002_adtracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adtracking',
            name='clicked',
        ),
        migrations.RemoveField(
            model_name='adtracking',
            name='downloaded',
        ),
        migrations.AddField(
            model_name='adtracking',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='adtracking',
            name='downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
